### ISSUE TITLE
Write a Calculator Program for Conditional and Loop in Calculator.java

### ISSUE THREAD

**Issue by moizsheraz** [moizsheraz/DSA-MasterCourse#1]
Write a Calculator Program for Conditional and Loop in Calculator.java

**Comment by gautham2k3** [comment]
Writing that code.

**Comment by gautham2k3** [comment]
are you sure about this "_does not start until unless user Enter X,x_"  
![Screenshot 2023-04-25 184309](https://user-images.githubusercontent.com/112716884/234287484-eee69b53-406b-4a4c-9ea2-223aa6c85761.png)

**Comment by moizsheraz** [comment]
yes

**Comment by moizsheraz** [comment]
should I assign the issue to you?
